# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d417390f0e90af9a6eda9760ba7a13ba5a9d38584732a67e227135a55e8cf614da43c4f55f9e127bc840fe0a2ac7f818893427d74e22cbbb495e544bba755ff4

test:
  secret_key_base: 036a7ca4725f980928826bfc83eb4400954f33b227ebb2fc7c4213d1ebd2654e5db703c1e2de657bd3520a7cf0c882661114a66a9ab87344561341e82316dd4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
